// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: game.sql

package database

import (
	"context"
)

const createNewGame = `-- name: CreateNewGame :one
INSERT INTO "Game" ("id", "player1Id" , "player2Id" ) values ($1, $2, $3) returning id, "player1Id", "player2Id"
`

type CreateNewGameParams struct {
	ID        string
	Player1Id string
	Player2Id string
}

func (q *Queries) CreateNewGame(ctx context.Context, arg CreateNewGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createNewGame, arg.ID, arg.Player1Id, arg.Player2Id)
	var i Game
	err := row.Scan(&i.ID, &i.Player1Id, &i.Player2Id)
	return i, err
}
