// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: message.sql

package database

import (
	"context"
)

const addMove = `-- name: AddMove :one
INSERT INTO "Move" ("id", "from" , "to", "timeStamp", "gameId", "color" ) values ($1, $2, $3, $4, $5, $6) returning id, "from", "to", "timeStamp", "gameId", color
`

type AddMoveParams struct {
	ID        string
	From      string
	To        string
	TimeStamp string
	GameId    string
	Color     string
}

func (q *Queries) AddMove(ctx context.Context, arg AddMoveParams) (Move, error) {
	row := q.db.QueryRowContext(ctx, addMove,
		arg.ID,
		arg.From,
		arg.To,
		arg.TimeStamp,
		arg.GameId,
		arg.Color,
	)
	var i Move
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.TimeStamp,
		&i.GameId,
		&i.Color,
	)
	return i, err
}
