// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Game struct {
	ID        string
	Player1Id string
	Player2Id string
}

type Move struct {
	ID        string
	From      string
	To        string
	TimeStamp string
	GameId    string
	Color     string
}

type User struct {
	ID           string
	Username     string
	Email        string
	Password     string
	RefreshToken string
}
